export const clinic = {
  name: 'Canby Community Clinic',
  organization: 'Pura Vida Community Clinic',
  phoneDisplay: '(818) 674-4414',
  phoneHref: 'tel:+18186744414',
  addressLine1: '7601 Canby Ave #6B',
  addressLine2: 'Reseda, CA 91335',
  hours: 'Monday–Friday · 9 AM–5 PM',
  directions: 'https://www.google.com/maps/search/?api=1&query=7601+Canby+Ave+%236B+Reseda+CA+91335',
  publicEmail: 'info@canbycc.org',
  formEmail: 'office@canbycc.org',
};

export const walkInPolicy = {
  title: 'Thinking of stopping by?',
  lead: 'Call before traveling to ask whether the clinic can accommodate a walk-in. Same-day availability and waiting times are not confirmed on this website.',
};

export const stories = {
  services: {
    variant: 'services',
    kicker: 'Care services · one connected practice',
    title: 'Care at Canby.',
    lead: 'A checkup, a vaccine, a blood test, or a medicine you already take. If you need care elsewhere, we can help you with the next step.',
    asset: '/assets/scenes/s-01-consultation.png',
    assetId: 'S-01',
    alt: 'A representative clinician listening to a patient in a community clinic consultation room.',
    sceneLabel: 'The care hallway',
    sectionKicker: 'Care services',
    sectionTitle: 'Our services.',
    items: [
      { label: 'Checkups · follow-up', title: 'Primary care', copy: 'A checkup, a weekday concern, follow-up, or a question about a medicine.', detail: 'For adults in Reseda. <a href="/articles/prepare-for-a-first-clinic-visit/">What to bring to a first clinic visit</a>.' },
      { label: 'Diabetes · pressure · cholesterol', title: 'Specialty care', copy: 'Follow-up when you already know you have diabetes, high blood pressure, or high cholesterol.', detail: 'Women’s checkups are part of care here too.' },
      { label: 'Blood pressure · cholesterol', title: 'Preventive care', copy: 'Blood pressure, diabetes risk, and cholesterol screenings, matched to your age and history.', detail: '<a href="/articles/questions-to-ask-about-blood-pressure/">Questions to ask about a blood pressure reading</a>.' },
      { label: 'Immunizations', title: 'Vaccines', copy: 'Vaccines given at the clinic. Call and ask which ones are available.', detail: '' },
      { label: 'Labs', title: 'Blood tests', copy: 'Blood tests done as part of a visit.', detail: 'We tell you how you will hear the result.' },
      { label: 'Prescriptions', title: 'Medication support', copy: 'Help understanding a prescription you already take.', detail: 'Bring the bottles or a current list. <a href="/articles/how-to-make-a-medication-list/">How to make a medication list</a>.' },
      { label: 'Lab orders · results', title: 'Testing and referrals', copy: 'When a test is not done here, we tell you where it is done and how you hear the result.', detail: '<a href="/articles/how-a-clinic-referral-works/">How a clinic referral works</a>.' },
      { label: 'Results · next steps', title: 'Health education', copy: 'What a result, a medicine, or the next step means.', detail: '' },
      { label: 'Programs · specialists', title: 'Care navigation', copy: 'Help finding a public program, a specialist, or another community resource when this clinic cannot provide the service.', detail: '' },
    ],
    finalTitle: 'Unsure where to begin?',
    finalCopy: 'Call the clinic. A team member can help you understand which starting point may fit your question and what availability to confirm.',
  },
  appointments: {
    variant: 'appointments',
    kicker: 'Appointments · a clear entrance',
    title: 'Arrange your visit.',
    lead: 'A visit starts with a request, continues with confirmation, and becomes easier when you know what to bring.',
    asset: '/assets/scenes/a-01-entrance.png',
    assetId: 'A-01',
    alt: 'An open accessible clinic entrance leading toward a modest reception desk.',
    sceneLabel: 'The entrance sequence',
    sectionKicker: 'Four moments in order',
    sectionTitle: 'From request to arrival.',
    items: [
      { label: '01 · Request', title: 'Tell us what you need.', copy: 'Share a reason for the visit and a preferred day and time.', detail: 'Use the visit form and pick a day and time.' },
      { label: '02 · Hear back', title: 'If that day is full.', copy: 'We\'ll offer another. You don\'t have to fill the form out again.', detail: '' },
      { label: '03 · Prepare', title: 'Bring the useful details.', copy: 'Photo ID, a medication list, and relevant records help us keep a more accurate history.', detail: 'Ask about accommodations, language help, or other access needs before the visit.' },
      { label: '04 · The door', title: 'Can\'t find the suite?', copy: 'Call from the parking lot. Someone will walk you to 6B.', detail: '' },
    ],
    finalTitle: 'Call to arrange your visit.',
    finalCopy: 'Call to request a visit. The clinic will explain availability and confirmation.',
  },
  'new-patients': {
    variant: 'new-patients',
    kicker: 'New patients · your first visit',
    title: 'Your first visit.',
    lead: 'Know what to share, what to bring, and what to ask before you leave home.',
    asset: '/assets/scenes/n-01-preparation.png',
    assetId: 'N-01',
    alt: 'Hands preparing a blank identification card, medication containers, records, glasses, and a pen on a table.',
    sceneLabel: 'The first-visit table',
    sectionKicker: 'Four things to prepare',
    sectionTitle: 'What to bring.',
    items: [
      { label: 'Before', title: 'Reason for your visit', copy: 'Describe the main question or concern in your own words.', detail: 'You do not need to diagnose yourself before calling.' },
      { label: 'Bring', title: 'ID, medications, records', copy: 'Bring photo ID, an updated medication list, and relevant records when available.', detail: 'Do not send sensitive medical information through an unapproved form.' },
      { label: 'Ask', title: 'Questions that matter', copy: 'Write down the questions you do not want to forget.', detail: 'Ask again if a word or a step is unclear.' },
      { label: 'Leave with', title: 'A visible next step', copy: 'Confirm what happens next, when to follow up, and who to contact.', detail: 'Before leaving, ask how results or referrals will be communicated.' },
    ],
    finalTitle: 'You do not have to arrive knowing everything.',
    finalCopy: 'Bring the information you have and the questions that matter. The first job is to begin the conversation.',
  },
  resources: {
    variant: 'resources',
    kicker: 'Patient resources · information with direction',
    title: 'Questions we hear.',
    lead: 'Use the resource desk to prepare for a visit, ask better questions, and understand practical follow-through.',
    asset: '/assets/scenes/r-01-resources.png',
    assetId: 'R-01',
    alt: 'A hand selecting one of six blank patient resource folders from a wooden clinic organizer.',
    sceneLabel: 'The resource desk',
    sectionKicker: 'Six practical guides',
    sectionTitle: 'Choose what you need now.',
    items: [
      { label: 'Guide', title: 'Prepare for your first visit', copy: 'What to bring, what to write down, and what to ask before arriving.' },
      { label: 'Check', title: 'Confirm before you go', copy: 'Why a request is not confirmation and when calling again is useful.' },
      { label: 'Learn', title: 'Understand everyday health', copy: 'Use plain-language information to support—not replace—a clinical conversation.' },
      { label: 'Review', title: 'Medication questions', copy: 'Organize prescriptions, supplements, access concerns, and questions about safer use.' },
      { label: 'Follow through', title: 'Know what happens after', copy: 'Track results, referrals, medication changes, warning signs, and follow-up.' },
      { label: 'Rights', title: 'Privacy and patient rights', copy: 'The privacy notice, the notice of privacy practices, and the nondiscrimination notice are posted on this website.' },
    ],
    finalTitle: 'Still have a question?',
    finalCopy: 'If a guide does not answer your question, call the clinic and ask what to do next.',
  },
  visit: {
    variant: 'visit',
    kicker: 'Visit · Reseda, California',
    title: walkInPolicy.title,
    lead: walkInPolicy.lead,
    asset: '/assets/scenes/v-01-reseda.png',
    assetId: 'V-01',
    alt: 'A representative elevated view of a low-rise Reseda neighborhood street approaching a community clinic.',
    sceneLabel: 'The Reseda approach',
    sectionKicker: 'Three arrival checks',
    sectionTitle: 'Know where you are going.',
    items: [
      { label: 'Address', title: '7601 Canby Ave #6B', copy: 'Reseda, CA 91335', detail: '' },
      { label: 'Hours', title: 'Monday–Friday', copy: '9 AM–5 PM', detail: 'Hours can change.' },
      { label: 'Before leaving', title: 'Parking and the entrance', copy: 'Ask about parking and the entrance if you need them.', detail: 'Call if you need help finding the entrance.' },
    ],
    finalTitle: 'Find the clinic.',
    finalCopy: 'Open directions or call the clinic before traveling.',
  },
  'our-clinic': {
    variant: 'our-clinic',
    kicker: 'Our clinic · rooted in Reseda',
    title: 'About Canby.',
    lead: 'Canby Community Clinic is the nonprofit clinic in Suite 6B. Pura Vida Community Clinic is the older name on the logo, and the name on the federal record. Same door.',
    asset: '/assets/scenes/a-01-entrance.png',
    assetId: 'A-01',
    alt: 'The clinic entrance, not a portrait of staff.',
    sceneLabel: 'Suite 6B',
    sectionKicker: 'Reseda',
    sectionTitle: 'One clinic. Two names.',
    items: [
      { label: 'The door', title: 'Suite 6B', copy: '7601 Canby Ave, Reseda, CA 91335. Canby Community Clinic Inc. is the legal name.' },
      { label: 'The logo', title: 'Pura Vida', copy: 'Pura Vida Community Clinic is the doing-business-as name. If you knew us by that name, you are in the right suite.' },
      { label: 'The work', title: 'In the suite, and out in Reseda', copy: 'Checkups and follow-up here. Screenings at churches and schools. Blood drives with the American Red Cross.' },
    ],
    finalTitle: 'No portraits yet.',
    finalCopy: 'This page does not show staff. Call (818) 674-4414 and ask who you will see.',
  },
};
