import {clinic} from './content.mjs';
const phone='<a class="button" href="tel:+18186744414">Call (818) 674-4414 ↗</a>';
const route=(url,label)=>`<a class="detail-link" href="${url}">${label} ↗</a>`;
const section=(id,label,title,content)=>`<section class="band custom-detail" id="${id}"><header class="detail-heading"><p class="eyebrow">${label}</p><h2 class="headline">${title}</h2></header>${content}</section>`;
const cards=items=>`<div class="practical-grid">${items.map(([title,copy])=>`<article><h3>${title}</h3><p>${copy}</p></article>`).join('')}</div>`;
const faq=items=>`<div class="page-faq">${items.map(([q,a])=>`<details><summary>${q}</summary><div>${a}</div></details>`).join('')}</div>`;
const steps=items=>`<ol class="process-list">${items.map(([title,copy])=>`<li><h3>${title}</h3><p>${copy}</p></li>`).join('')}</ol>`;
const checklist=(items)=>`<div class="visit-checklist" data-checklist><p class="check-progress" aria-live="polite">0 of ${items.length} prepared</p>${items.map((item,i)=>`<label><input type="checkbox"><span><strong>${item[0]}</strong><span>${item[1]}</span></span></label>`).join('')}<div class="checklist-actions"><button class="button" data-print type="button">Print this checklist</button><button class="text-button" data-clear-checklist type="button">Clear checks</button></div><p class="form-note">Use this list for your own preparation. Checks are not sent to the clinic or saved after you leave.</p></div>`;
export function details(slug){
const content={
 services:section('care-questions','Before choosing care','Start with your concern.',cards([['A new or ongoing concern','A checkup, a weekday concern, or follow-up you already know you need.'],['Questions about medication','Bring your current prescriptions and supplements, or the original bottles.'],['An outside test or referral','Ask where the test is done and how you will hear the result.']])+`<div class="detail-callout"><h3>Some tests happen somewhere else.</h3><p>Outside tests and referrals can depend on eligibility, authorization, and another provider’s availability.</p>${phone}</div>`)+section('care-follow-up','After the conversation','Before you leave.',steps([['Write down the plan','Ask for the next step again if an instruction is unclear.'],['Check results and referrals','Ask how you will receive results and whom to contact about a referral.'],['Know when to follow up','Before leaving, ask the next action and who to contact with questions.']])+route('/resources/','Explore patient resources')),
 appointments:section('booking-options','Request a visit','Choose how to begin.',`<div class="choice-panels"><article><p class="eyebrow">By phone</p><h3>Speak with the clinic.</h3><p>Share your reason for visiting and a preferred day and time. Ask about availability, what to bring, and any access needs.</p>${phone}</article><article><p class="eyebrow">Visit form</p><h3>Request the visit.</h3><p>Use the visit form for a day and time at the clinic.</p>${route('/request-visit/','Request a visit')}</article></div>`)+section('appointment-questions','Planning ahead','Before you leave home.',faq([['What should I have ready?', 'Photo ID, an up-to-date medication list, relevant records when available, and the questions you want to discuss.'],['Can I ask about accommodations?', 'Ask about mobility access, communication support, language assistance, or other needs before your visit.'],['Where do I go?', '7601 Canby Ave #6B, Reseda, CA 91335. Ask the clinic about parking, the accessible entrance, and finding Suite 6B.'],['Do you handle emergency requests here?', 'This website is not monitored for emergencies. Call 911 when immediate emergency help is needed.']])+route('/new-patients/','Prepare for your first visit')),
 'new-patients':section('preparation-checklist','Your preparation list','Bring what you have.',`<div class="checklist-layout"><div><p class="large-copy">You do not need to arrive with every answer. Start with the information you have and the questions that matter.</p><p><a class="detail-link" href="/articles/prepare-for-a-first-clinic-visit/">What to bring to a first clinic visit</a></p><img class="detail-photo" src="/assets/scenes/n-01-preparation.webp" alt="Illustration of records and medications prepared for a visit" loading="lazy"></div>${checklist([['Reason for your visit','Describe your main question or concern in your own words.'],['Photo ID','Bring identification when available.'],['Medication list','Include prescriptions and supplements, or bring the original containers when possible.'],['Relevant records','Bring information that helps us keep a more accurate history.'],['Your questions','Write down what you do not want to forget.'],['Insurance card','Bring it if you have one. If you do not, say so on the visit form.']])}</div>`)+section('first-visit-questions','During your visit','Questions worth asking.',cards([['What happens next?','Ask about your next action and when to follow up.'],['How will I hear about results?','Confirm how test results or referrals will be communicated.'],['Who should I contact?','Write down where to direct questions about the plan.']])+route('/visit/','Find the clinic')),
 resources:section('practical-guides','Patient resource desk','Open the guide you need.',faq([['Prepare for your first visit', '<p>Write down your main concern, gather ID, medications and relevant records, and list your questions. Ask about access needs before arriving.</p>'+route('/new-patients/#preparation-checklist','Use the preparation checklist')],['Confirm before you go','<p>A visit request is the beginning of scheduling. Wait for confirmation and call before traveling if you have not heard back. Confirm the address and Suite 6B.</p>'+route('/appointments/','Understand the appointment steps')],['Organize medication questions','<p>Make a current list of prescriptions and supplements, or bring the original containers when possible. Include questions about access and instructions you want explained.</p>'+route('/services/#medication-support','Medication support')],['Follow through after your visit','<p>Write down your next step, when to follow up, how results will be shared, and who to contact about referrals. Ask for a plain-language explanation when needed.</p>'+route('/services/#care-navigation','Care navigation')],['Privacy, access, and patient information','<p>Ask the clinic for its current approved notices. Do not put medical records, diagnoses, test results, or insurance numbers in an ordinary email request.</p>'+route('/legal/privacy/','Website privacy information')+route('/legal/accessibility/','Accessibility information')]])),
 visit:section('arrival-details','Plan your arrival','The details for your visit.',`<div class="arrival-grid"><div class="address-panel"><p class="eyebrow">Canby Community Clinic</p><address>7601 Canby Ave<br><strong>Suite 6B</strong><br>Reseda, CA 91335</address><a class="button" href="https://www.google.com/maps/search/?api=1&query=7601+Canby+Ave+%236B+Reseda+CA+91335" target="_blank" rel="noopener">Open directions ↗</a></div><div><dl class="clinic-facts"><div><dt>Hours</dt><dd>Monday–Friday<br>9 AM–5 PM</dd></div><div><dt>Phone</dt><dd><a href="tel:+18186744414">(818) 674-4414</a></dd></div><div><dt>Email</dt><dd><a href="mailto:${clinic.publicEmail}">${clinic.publicEmail}</a></dd></div></dl></div></div>`)+section('access-and-parking','The building','Finding the clinic.',cards([['Need a hand?','Call us from the parking lot if you need help finding the entrance.'],['Parking and entrance','Call for current parking information and the accessible entrance.'],['Communication and access','Ask in advance about accommodations or language assistance.']])+route('/legal/accessibility/','Accessibility information')),
 'our-clinic':section('clinic-in-practice','A visit here','What people come in for.',`<div class="editorial-split"><img class="detail-photo" src="/assets/scenes/a-01-entrance.webp" alt="The clinic entrance at 7601 Canby Ave" loading="lazy"><div><p>Most people come for a checkup, a screening, or follow-up they already know they need. Bring a photo ID, your medicines, and the question you do not want to forget. If a test is not done in the suite, we tell you where it is done and how you will hear the result.</p></div></div>`)+section('community-participation','Part of the community','More than one way to help.',`<div class="choice-panels"><article><h3>Share your time and skills.</h3><p>Licensed clinicians and neighbors both help. The work depends on what the clinic needs that week.</p>${route('/volunteer/','Volunteer')}</article><article><h3>Give.</h3><p>A gift helps keep the clinic open in Reseda. Apple Pay, PayPal, Stripe, or a check mailed to Suite 6B.</p>${route('/give/','Donate')}</article></div>`),
 volunteer:section('volunteer-roles','Where your skills fit','Explore the work.',cards([['Clinical support','Licensed or appropriately trained volunteers can ask about work matched to their verified credentials and the clinic’s current needs.'],['Health education','Qualified volunteers may help prepare or deliver approved education activities. Individual advice must remain within an approved role.'],['Welcome and outreach','Ask about hospitality, outreach, events, and patient-facing navigation. Activities depend on current needs and training.'],['Practical operations','Organization, resource preparation, language support, and administrative skills may help. Access to information is limited to assigned duties.']]))+section('volunteer-review','Before placement','Before you start volunteering.',steps([['Choose your path','Complete the medical or non-medical interest form and prepare your email.'],['Send your message','Send the draft from your own email application. Preparing it alone does not submit your interest.'],['Discuss the role in person','Both pathways include clinic review and an in-person interview before placement.'],['Confirm scope and training','Medical roles require credential verification and supervision. All roles must follow assigned responsibilities and privacy requirements.']])+route('#apply','Go to the interest forms')),
 donate:section('giving-questions','Before giving','Know where your support goes.',faq([['Can I make a payment on this page?', 'Not yet. The amount selector and receipt are a demonstration. No card details are collected and no money is charged. Call the clinic for its approved giving destination.'],['What can community support help with?', 'The archive identifies patient access, education and resources, and clinic operations as potential priorities. Ask the clinic to confirm current programs and how gifts are used.'],['Can I choose a monthly amount?', 'You can preview a monthly amount here. It does not create a subscription or schedule a payment.'],['Will I receive a tax receipt?', 'The preview receipt is not a payment or tax receipt. Confirm tax status, deductibility, and receipt arrangements directly with the clinic before giving.'],['Is there another way to help?', '<p>Explore medical and non-medical volunteer pathways, or call to ask what is needed now.</p>'+route('/volunteer/','Explore volunteering')]])),
 'request-visit':section('visit-at-the-clinic','At the clinic','Where the visit happens.',`<p class="large-copy">7601 Canby Ave #6B, Reseda. Monday–Friday, 9 AM–5 PM.</p>${phone}`)
};
if(slug.startsWith('legal/'))return section('notice-help','A paper copy','Want this read to you, or on paper?',`<div class="notice-contact"><p>Call the clinic and ask. We can read a notice to you or give you a paper copy.</p>${phone}${route('/visit/','Address and visit information')}</div>`);
return content[slug]||'';
}
