import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {clinic,stories,walkInPolicy} from './content.mjs';
import {revisedPage,menuItems,menuLine,menuLanguage} from './revisions.mjs';
import {details} from './details.mjs';
import {installArticles} from './install-articles.mjs';
process.chdir(fileURLToPath(new URL('..',import.meta.url)));
const labels={services:'Services',appointments:'Appointments','new-patients':'New patients',resources:'Resources',visit:'Visit','our-clinic':'Our clinic',volunteer:'Volunteer',donate:'Donate','request-visit':'Request a visit'};
const legal=JSON.parse(readFileSync('scripts/legal.json'));
const link=(slug,label)=>`<a href="/${slug==='donate'?'give':slug}/">${label||labels[slug]}</a>`;
const call=`<a class="button" href="${clinic.phoneHref}">Call ${clinic.phoneDisplay} ↗</a>`;
const appointmentLinks=[['/appointments/walk-ins/','Walk-in'],['/visit/in-home/','Request an in-home visit'],['/request-visit/','Office visit']];
const careLinks=[['/services/#primary-care','Primary care'],['/services/#specialty-care','Specialty care'],['/services/#preventive-care','Preventive care'],['/services/#vaccines','Vaccines'],['/services/#blood-tests','Blood tests'],['/services/#medication-support','Medication support'],['/services/#testing-and-referrals','Testing and referrals'],['/services/#health-education','Health education'],['/services/#care-navigation','Care navigation']];
const resourceLinks=[['https://211la.org/needhelp','Food and shelter — 211 LA'],['https://www.coveredca.com/enrollment','Health coverage — Covered California'],['https://www.dhcs.ca.gov/medi-cal/apply/','Apply for Medi-Cal'],['https://988lifeline.org/','988 crisis line'],['/resources/','All community resources']];
const dropdown=(name,items)=>`<li class="nav-group"><details class="nav-dropdown"><summary><span data-nav-label>${name}</span></summary><ul class="nav-submenu">${items.map(([url,label])=>`<li><a href="${url}" ${url.startsWith('https:')?'target="_blank" rel="noopener"':''} data-nav-label>${label}</a></li>`).join('')}</ul></details></li>`;
const nav=dropdown('Appointments',appointmentLinks)+dropdown('Care',careLinks)+dropdown('Resources',resourceLinks)+dropdown('Support Us',[['/give/','Donate'],['/volunteer/','Volunteer']])+`<li><a href="/articles/" data-nav-label>Articles</a></li><li><a href="/our-clinic/" data-nav-label>Our clinic</a></li><li><a href="/visit/" data-nav-label>Visit</a></li>`;
const languageSelector=`<label class="site-language"><span class="visually-hidden">Navigation language</span><select data-site-language aria-label="Navigation language"><option value="en">EN</option><option value="es">ES</option><option value="hy">ՀԱՅ</option></select></label>`;
const preloader=`<div class="logo-preloader" hidden aria-label="Loading Canby Community Clinic" role="status"><img src="/assets/logo/canby-logo-transparent.png" alt="Canby Community Clinic" width="1529" height="608" fetchpriority="high"></div><script src="/preloader.js"></script>`;
const header=`<header class="site-header"><div class="bar" data-inert-with-menu><a class="wordmark" href="/"><img class="clinic-logo" src="/assets/logo/canby-logo-transparent.png" width="1529" height="608" alt="Canby Community Clinic — Pura Vida Community Clinic"></a><nav class="desktop-nav" aria-label="Primary"><ul>${nav}</ul></nav><a class="button button-paper bar-appointment" href="/request-visit/">Request a visit</a>${languageSelector}<button class="button button-paper menu-toggle" data-menu-open aria-expanded="false" aria-controls="site-menu">Menu</button></div><div id="site-menu" class="menu-overlay" role="dialog" aria-modal="true" aria-label="Menu" data-menu-overlay hidden><button class="button button-paper" data-menu-close>Close menu ×</button><nav aria-label="Mobile"><ul class="menu-list">${nav}<li>${link('request-visit')}</li></ul></nav>${call}</div></header>`;
const footer=`<footer class="site-footer" data-inert-with-menu><div class="footer-cols"><div class="footer-contact"><a class="wordmark" href="/"><img class="clinic-logo" src="/assets/logo/canby-logo-transparent.png" width="1529" height="608" alt="Canby Community Clinic — Pura Vida Community Clinic"></a><p>Community care in Reseda.</p><p>7601 Canby Ave #6B<br>Reseda, CA 91335</p><p>Monday–Friday · 9 AM–5 PM</p><a href="${clinic.phoneHref}">${clinic.phoneDisplay}</a><p><a href="mailto:${clinic.publicEmail}">${clinic.publicEmail}</a></p><p>For emergencies, call 911.</p></div><nav class="footer-link-column" aria-label="Explore the clinic"><h2 class="footer-heading">Explore</h2>${Object.keys(labels).slice(0,6).map(k=>link(k)).join('')}<a href="/articles/">Articles</a><a href="/insurance/">Insurance</a></nav><nav class="footer-link-column" aria-label="Support and clinic information"><h2 class="footer-heading">Support &amp; information</h2>${link('volunteer')}${link('donate')}${link('request-visit')}${Object.entries(legal).map(([k,v])=>link('legal/'+k,v[1])).join('')}</nav></div><div class="footer-bottom"><p><a href="mailto:usscallisterllc@gmail.com">Website by USSCALLISTER</a></p><p>© 2026 Canby Community Clinic</p></div></footer>`;
const head=(title)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${title} | Canby Community Clinic</title><meta name="description" content="${title} at Canby Community Clinic in Reseda, California.">${['tokens','base','home','clinic','pages'].map(f=>`<link rel="stylesheet" href="/src/styles/${f}.css">`).join('')}</head><body class="inner-page"><a class="skip" href="#main">Skip to content</a>${preloader}${header}<main id="main" data-inert-with-menu>`;
const end=`</main>${footer}<script type="module" src="/src/pages.js"></script></body></html>`;
const pages=[];
function page(slug,title,body){if(['donate','appointments/in-home-visit','appointments/office-visit'].includes(slug))return;body=revisedPage(slug,body);if(slug==='visit')body=body.replace('src="/assets/scenes/v-01-reseda.webp" alt="Illustrative clinic scene"','src="/assets/scenes/community-circle.png" alt="Illustrative aerial view of neighbors holding hands in a circle"');if(slug==='give'){const start=body.indexOf('<section class="band band-paper">');const pay=body.indexOf('<section class="band band-ground donation-section">');if(start>=0&&pay>=0)body=body.slice(0,start)+body.slice(pay)+body.slice(start,pay);}const extra=['appointments','volunteer','give','visit/in-home','insurance','articles','resources','our-clinic'].includes(slug)?'':details(slug);const closing=body.lastIndexOf('<section class="band band-ink page-close">');body=closing<0?body+extra:body.slice(0,closing)+extra+body.slice(closing);mkdirSync(slug,{recursive:true});writeFileSync(slug+'/index.html',head(title).replace('class="inner-page"',`class="inner-page route-${slug.replaceAll('/','-')}"`)+body+end);pages.push(slug)}
const hero=(eyebrow,title,copy,asset,action=link('request-visit','Request a visit ↗'))=>`<section class="page-hero"><div><p class="eyebrow">${eyebrow}</p><h1 class="headline">${title}</h1><p class="page-lead">${copy}</p><div class="page-actions">${action}</div></div>${asset?`<img src="/assets/scenes/${asset}.webp" alt="Illustrative clinic scene">`:''}</section>`;
const signature=(slug,s)=>{
 if(slug==='appointments')return '';
 if(slug==='visit')return `<section class="route-stage approach-stage"><div class="stage-sticky"><div class="approach-frame"><img src="/assets/scenes/care-navigation.png" alt="Canby Community Clinic entrance guide showing Suite 6B, the main entrance, and the parking lot entrance"></div><div class="stage-copy"><p class="eyebrow">Parking and entrance</p><h2 class="headline">7601 Canby Avenue.</h2><a class="button button-paper" href="${clinic.directions}">Open directions ↗</a></div></div></section>`;
 return '';
};
const close=(title,copy)=>`<section class="band band-ink page-close"><h2 class="headline">${title}</h2><p>${copy}</p>${call}</section>`;
for(const [slug,s] of Object.entries(stories)){
 let items=s.items.map((x,i)=>`<article class="detail-row" id="${x.title.toLowerCase().replaceAll(' ','-')}"><div><p class="eyebrow">${x.label}</p><h3>${x.title}</h3></div><div><p>${x.copy}</p>${x.detail?`<p class="detail-note">${x.detail}</p>`:''}${slug==='resources'?link(['new-patients','appointments','services','services/#medication-support','services/#care-navigation','visit'][i].replace('/#','#'), 'Read more ↗'):''}</div></article>`).join('');
 // Explicit resource targets avoid appending a slash after fragment identifiers.
 items=items.replace('/services#medication-support/','/services/#medication-support').replace('/services#care-navigation/','/services/#care-navigation');
 page(slug,labels[slug],hero(labels[slug]+' / Reseda',s.title,s.lead,s.asset.split('/').pop().replace('.png',''))+signature(slug,s)+(slug==='appointments'?`<nav class="band appointment-options" aria-label="Appointment types">${appointmentLinks.map(([url,title])=>`<a href="${url}">${title}<span aria-hidden="true">↗</span></a>`).join('')}</nav>`:'')+`<section class="band band-paper"><h2 class="headline section-title">${s.sectionTitle}</h2>${items}${slug==='visit'?`<a class="button" href="${clinic.directions}" target="_blank" rel="noopener">Get directions ↗</a>`:''}</section>`+close(s.finalTitle,s.finalCopy));
}
const input=(name,label,type='text',required=true)=>`<label>${label}<input name="${name}" type="${type}" ${required?'required':''} ${type==='email'?'autocomplete="email"':type==='tel'?'autocomplete="tel"':''}></label>`;
const select=(name,label,options)=>`<label>${label}<select name="${name}" required>${options.map(x=>`<option>${x}</option>`).join('')}</select></label>`;
const emailForm=(kind,fields,consent,button='Prepare email ↗')=>`<form class="email-form" data-inbox="office" data-subject="${kind}"><div class="form-grid">${input('Full name','Full name')}${input('Email','Email','email')}${input('Phone','Phone','tel')}${fields}</div><label class="check"><input type="checkbox" required> ${consent}</label><button class="button" type="submit">${button}</button><p class="form-note">This prepares a message to ${clinic.formEmail}. You must send it from your email app.</p><div class="email-result" hidden role="status"><h3>Your email is ready.</h3><p>Open the draft below and send it from your email app to finish. Preparing a draft does not submit a request.</p><a class="button email-draft">Open email draft ↗</a><details><summary>No email app? Copy your message</summary><textarea readonly aria-label="Prepared email message"></textarea><p>Send to ${clinic.formEmail}, or call (818) 674-4414.</p></details><button type="reset" class="text-button">Clear and start again</button></div></form>`;
page('appointments/in-home-visit','Request an in-home visit',hero('Appointments / In-home requests','Request care at home.','Contact the clinic to ask whether an in-home visit is available for your needs and location. A request does not confirm a visit.','a-01-entrance','<a href="#home-request">Prepare a request ↓</a>')+`<section class="band band-paper form-section" id="home-request"><div><h2>Ask about an in-home visit</h2><p>Share contact details and your city or ZIP code. The clinic will need to confirm availability, service area, and whether a home visit is appropriate. Do not include medical details or your street address in this email request.</p>${emailForm('In-home visit availability request',input('City or ZIP code','City or ZIP code')+select('Preferred contact','Preferred contact',['Phone call','Email'])+input('Best callback time','Best callback time'),'I understand in-home availability must be confirmed by the clinic.')}</div><aside><h2>Confirm before making plans.</h2><p>Ask about scheduling, eligibility, fees, and what information the clinic needs. In-home visits are not confirmed through this website.</p>${call}<p>For emergencies, call 911.</p></aside></section>`);
page('appointments/walk-ins','Walk-ins',hero('Appointments / Walk-ins',walkInPolicy.title,walkInPolicy.lead,'a-01-entrance',call)+`<section class="band band-paper"><h2 class="headline section-title">Before you come in.</h2><div class="practical-grid"><article><h3>Call about availability.</h3><p>${walkInPolicy.lead}</p></article><article><h3>Confirm hours and location.</h3><p>Monday–Friday, 9 AM–5 PM. 7601 Canby Ave #6B, Reseda, CA 91335. Hours can change; confirm before visiting.</p></article><article><h3>Bring useful details.</h3><p>Bring photo ID, a current medication list, relevant records when available, and your questions.</p></article></div><div class="confirmation-note"><strong>Prefer a planned visit?</strong><p>Use the visit form. It is the same form as the button in the header.</p><a class="detail-link" href="/request-visit/">Request a visit ↗</a></div><a class="detail-link" href="/visit/">Directions and arrival details ↗</a></section>`);
page('appointments/office-visit','Book an office visit',hero('Appointments / Office visits','Plan your office visit.','Share a preferred day and time, then wait for the clinic to confirm availability. This form prepares an email request; it does not reserve an appointment.','s-01-consultation','<a href="#office-request">Request an appointment ↓</a>')+`<section class="band band-paper form-section" id="office-request"><div><h2>Request an office appointment</h2><p>Use basic scheduling and contact details only. Discuss your medical concerns directly with the clinic.</p>${emailForm('Office visit appointment request',input('Preferred day','Preferred day','date')+input('Preferred time','Preferred time','time')+select('Patient status','Patient status',['New patient','Existing patient'])+select('Preferred contact','Preferred contact',['Phone call','Email']),'I understand my appointment is not booked until the clinic confirms it.')}</div><aside><h2>Your visit in Reseda</h2><p>7601 Canby Ave #6B<br>Reseda, CA 91335</p><p>Monday–Friday · 9 AM–5 PM</p>${call}<a class="detail-link" href="/new-patients/#preparation-checklist">Prepare for your visit ↗</a></aside></section>`);
page('request-visit','Request a visit',hero('Visit','Request a visit.','Tell us when you would like to come in. We will contact you to confirm an available appointment.','','<a href="#visit-form">Go to the form ↓</a>')+`<section class="band band-paper form-section" id="visit-form"><div><h2>Visit request</h2><p>Request a checkup, follow-up, or medication review. Do not include medical records.</p>${emailForm('Visit request',select('Patient status','Patient status',['New patient','Returning patient'])+select('Visit','Visit',['Checkup','Follow-up','Medication review','Vaccine','Blood test','Other'])+input('Preferred day','Preferred day','date')+input('Preferred time','Preferred time','time')+select('Language','Language',['English','Spanish','Armenian']),'Please use this information to request my visit.','Request visit')}</div><aside><h2>Clinic</h2><p>7601 Canby Ave #6B<br>Reseda, CA 91335</p><p>Monday–Friday · 9 AM–5 PM</p>${call}<a class="detail-link" href="/appointments/walk-ins/">Walk-in</a><a class="detail-link" href="/visit/in-home/">In-home visit</a></aside></section>`);
page('volunteer','Volunteer',hero('Volunteer / Community','Bring your skills closer to care.','Medical and non-medical volunteers can help in different ways. Start with current needs, a clear scope, and clinic approval.','vol-01-community','<a href="#apply">Explore volunteer paths ↓</a>')+`<section class="band band-paper"><div class="split-grid"><div><p class="eyebrow">Medical volunteers</p><h2>Clinical and education support</h2><p>Ask about opportunities suited to your training and credentials. Clinical roles require credential verification, supervision, privacy training, and an approved scope.</p></div><div><p class="eyebrow">Non-medical volunteers</p><h2>Welcome, outreach, and operations</h2><p>Ask about hospitality, resource preparation, language support, or administrative work. Available roles depend on current needs and training.</p></div></div></section><section class="band band-ground" id="apply"><p class="eyebrow">Volunteer interest</p><h2 class="headline section-title">Two ways to help.</h2><div class="volunteer-forms"><section><h3>Medical volunteer interest</h3><p>Share your credentials. Submitting interest does not authorize clinical work.</p>${emailForm('Medical volunteer interest',input('Professional role','Professional role')+input('License or credential','License or credential')+input('Availability','Typical availability'),'I understand an in-person interview and clinic approval are required before volunteering.')}</section><section><h3>Non-medical volunteer interest</h3><p>Tell the clinic how you would like to help.</p>${emailForm('Non-medical volunteer interest',select('Area of interest','How would you like to help?',['Welcome and registration','Community outreach','Interpretation','Administrative help','Events and supplies'])+input('Languages','Languages', 'text',false)+input('Availability','Typical availability'),'I understand an in-person interview and clinic approval are required before volunteering.')}</section></div></section>`+close('Start by asking what is needed.','Call to confirm whether volunteer applications are currently being accepted.'));
page('donate','Donate',hero('Give / Community support','Help care move forward.','Support for patient access, practical resources, and the everyday work of community care. Contact the clinic to confirm current giving options.','d-01-giving','<a href="#giving">Explore giving ↓</a>')+`<section class="band band-paper" id="giving"><h2 class="headline section-title">Support with a purpose.</h2><div class="giving-priorities"><article><h3>Patient access</h3><p>Help address practical barriers to beginning care.</p></article><article><h3>Education and resources</h3><p>Help people prepare, understand, and follow through.</p></article><article><h3>Clinic operations</h3><p>Support the materials and everyday work behind care.</p></article></div><p class="detail-note">Contact the clinic to confirm current funding priorities, donation instructions, and tax information.</p></section><section class="band band-ground donation-section" id="donate-test"><div><p class="eyebrow">Donation preview</p><h2 class="headline">Choose how<br>you’d give.</h2><p>This demo does not accept payments. For a real donation, call the clinic for its approved giving destination.</p>${call}</div><form id="donation-form"><p class="demo-label">Demo only · No money is charged</p><fieldset><legend>Frequency</legend><div class="choice-row"><label><input type="radio" name="frequency" value="One time" checked> One time</label><label><input type="radio" name="frequency" value="Monthly"> Monthly</label></div></fieldset><fieldset><legend>Donation amount (USD)</legend><div class="amounts">${[25,50,100,250].map(n=>`<label><input type="radio" name="amount" value="${n}" ${n===50?'checked':''}> $${n}</label>`).join('')}<label><input type="radio" name="amount" value="other"> Other</label></div><label id="custom-amount-label" hidden>Amount in USD<input id="custom-amount" type="number" min="1" max="100000" step="0.01" inputmode="decimal" disabled></label></fieldset><fieldset><legend>Preview payment option</legend><div class="choice-row"><label><input type="radio" name="method" value="Card" checked> Card</label><label><input type="radio" name="method" value="PayPal"> PayPal</label></div></fieldset><p class="donation-total">Demo total <output id="donation-total">$50.00</output></p><p class="form-note">No card or personal information is needed for this preview. Neither payment provider is connected.</p><button class="button" type="submit">Preview donation receipt ↗</button><section id="donation-receipt" hidden role="status" tabindex="-1"><h3>Your demo receipt</h3><p id="receipt-summary"></p><p>No donation was submitted and no money was charged.</p><button type="reset" class="text-button">Try another amount</button></section></form></section>`);
const h2=t=>`<h2>${t}</h2>`;
const para=t=>`<p>${t}</p>`;
const items=list=>`<ul>${list.map(t=>`<li>${t}</li>`).join('')}</ul>`;
const notice=(parts)=>hero('Clinic information',parts.title,parts.lead)+`<article class="band band-paper legal-copy">${parts.body}</article>`;
const clinicContact=`Privacy Officer, Canby Community Clinic, 7601 Canby Ave #6B, Reseda, CA 91335. Call ${clinic.phoneDisplay} or email ${clinic.publicEmail}.`;
const notices={
 'notice-of-privacy-practices':notice({title:'Notice of privacy practices',lead:'Effective October 8, 2026.',body:
  para('THIS NOTICE DESCRIBES HOW MEDICAL INFORMATION ABOUT YOU MAY BE USED AND DISCLOSED AND HOW YOU CAN GET ACCESS TO THIS INFORMATION. PLEASE REVIEW IT CAREFULLY.')+
  para('Canby Community Clinic, formerly Pura Vida Community Clinic, keeps a record of the care we provide. This notice says how we may use and share that information, and what you can ask us to do.')+
  h2('How we may use and share it')+
  items([
    'Treatment. To provide a checkup, screening, follow-up, or medicine review, and to coordinate a test or a referral.',
    'Payment. To bill you or a health plan, if you are using insurance.',
    'Clinic operations. To schedule visits, train the people who work here, and improve how the clinic runs.'
  ])+
  para('We may also share information when the law requires it, for public health, for health oversight, to avert a serious threat, or for workers’ compensation. We do not sell your medical information. We do not use it for marketing unless you sign an authorization.')+
  h2('This website')+
  para('The forms on this website do not save what you type. They open a draft in your email app. The clinic does not have it until you send the email. Do not put a diagnosis, a record, or an insurance number in that email. Email is not a private way to send medical information. Call the clinic instead.')+
  h2('Your rights')+
  items([
    'See or get a copy of the record we keep about you.',
    'Ask us to correct something you think is wrong.',
    'Ask for a list of certain times we shared your information.',
    'Ask us to limit what we share. We will say yes when the law requires it.',
    'Ask us to contact you in a particular way, or at a particular place.',
    'Get a paper copy of this notice. Ask at the clinic or call us.',
    'File a complaint if you think your privacy was not protected. We will not retaliate.'
  ])+
  para('California law, including the Confidentiality of Medical Information Act, also limits how medical information may be shared.')+
  h2('Our duties')+
  para('We must keep your medical information private, give you this notice, and follow it. If the law requires us to tell you about a breach of unsecured medical information, we will. We may change this notice. The new notice will apply to information we already have, and we will post it here.')+
  h2('Complaints and questions')+
  para(clinicContact)+
  para('You may also file a complaint with the U.S. Department of Health and Human Services, Office for Civil Rights, at <a href="https://www.hhs.gov/hipaa/filing-a-complaint/index.html">hhs.gov/hipaa/filing-a-complaint</a> or 1-800-368-1019.')
 }),
 privacy:notice({title:'Privacy',lead:'What this website does with information you give it.',body:
  para('This page is about the website. How we use medical information from your care is in the <a href="/legal/notice-of-privacy-practices/">notice of privacy practices</a>.')+
  h2('What we collect')+
  para('You can read this site without giving us your name. There is no account and no patient portal here.')+
  para('A visit request, an appointment request, an in-home request, or a volunteer form opens a draft in your own email app, addressed to office@canbycc.org. We do not store the form on the website. If you do not send the email, we never receive it.')+
  para('Do not put a diagnosis, test result, record, or insurance number in a website email. Call (818) 674-4414 for anything about your health.')+
  h2('Email you send us')+
  para('Mail to info@canbycc.org and office@canbycc.org is read by the clinic. Ordinary email can be seen by other people while it travels. Do not use it for private medical details.')+
  h2('What we do not do')+
  para('We do not sell personal information. We do not ask this website to follow you with advertising cookies. A page may remember a choice you make in the browser, such as the language of the menu, only for that visit.')+
  h2('Questions')+
  para(clinicContact)
 }),
 nondiscrimination:notice({title:'Nondiscrimination',lead:'Care at Canby is for the person in front of us.',body:
  para('Canby Community Clinic complies with applicable Federal civil rights laws and does not discriminate on the basis of race, color, national origin, age, disability, or sex. Sex includes pregnancy, sexual orientation, and gender identity.')+
  para('We also do not discriminate because of religion, ancestry, marital status, or medical condition.')+
  h2('Help is free')+
  para('If you need help to talk with us, or to read something we give you, call (818) 674-4414. We can arrange a qualified interpreter, or information in another format, at no cost to you.')+
  para('ATENCIÓN: Si habla español, tiene a su disposición servicios gratuitos de asistencia lingüística. Llame al (818) 674-4414.')+
  para('ՈՒՇԱԴՐՈՒԹՅՈՒՆ. Եթե խոսում եք հայերեն, լեզվական օգնությունը անվճար է: Զանգահարեք (818) 674-4414.')+
  h2('If you believe we treated you unfairly')+
  para('Write or call the Civil Rights Coordinator, Canby Community Clinic, 7601 Canby Ave #6B, Reseda, CA 91335, (818) 674-4414, info@canbycc.org. We will not retaliate.')+
  para('You can also file a civil rights complaint with the U.S. Department of Health and Human Services, Office for Civil Rights, at <a href="https://ocrportal.hhs.gov/ocr/smartscreen/main.jsf">ocrportal.hhs.gov</a> or 1-800-368-1019.')
 })
};
for(const [slug,v] of Object.entries(legal)){
 const title=v[1];
 if(notices[slug]){page('legal/'+slug,title,notices[slug]);continue;}
 const paragraphs=v.slice(2,v.indexOf('Community-centered care and practical patient support in Reseda.'));
 page('legal/'+slug,title,hero('Clinic information',title,'')+`<article class="band band-paper legal-copy">${paragraphs.map(p=>`<p>${p}</p>`).join('')}${call}</article>`);
}
for(const [slug,title] of [['visit/in-home','In-home visit'],['give','Donate'],['insurance','Insurance']])page(slug,title,'');
page('404','Page not found',hero('Page not found','Let’s get you to the right place.','This address does not match a page on the updated site.',null,'<a href="/">Back to the homepage ↗</a>')+`<section class="band band-paper sitemap-links">${Object.keys(labels).map(k=>link(k)).join('')}<a href="/articles/">Articles</a></section>`);
installArticles({header,footer,preloader,pages});
let home=readFileSync('scripts/home.html','utf8').replace(/<header class="site-header">[\s\S]*?<\/header>/,header).replace(/<footer class="site-footer"[\s\S]*?<\/footer>/,footer).replace('</head>','<link rel="stylesheet" href="/src/styles/pages.css"></head>');
// Replace the old single-page navigation with dedicated page destinations.
home=home.replaceAll('href="#first-visit"','href="/new-patients/"').replaceAll('href="#our-clinic"','href="/our-clinic/"');
home=home.replace('<body>','<body>'+preloader);
home=home.replace('Call to request a visit ↗','Request a visit');
home=home.replace(/<a class="button button-paper" href="tel:\+18186744414">Call to request a visit[\s\S]*?<\/a>/,'<a class="button button-paper" href="/request-visit/">Request a visit</a>');
home=home.replace('<p class="gallery-note">Explore all services <span aria-hidden="true">→</span></p>','<p class="gallery-note"><a href="/services/">Explore all services →</a></p>');
home=home.replace('<section class="band-ink close-band">','<section class="band band-paper support-links"><div><p class="eyebrow">Community support</p><h2 class="headline">Be part of the care.</h2></div><div><a href="/volunteer/">Volunteer your time ↗</a><a href="/give/">Support the clinic ↗</a></div></section><section class="band-ink close-band">');
writeFileSync('index.html',home);
const aliases={'donate':'/give/','appointments/in-home-visit':'/visit/in-home/','appointments/office-visit':'/request-visit/','CanbyCLinic-Admin/donate':'/give/','about':'/our-clinic/','contact':'/visit/','donation':'/give/','donations':'/give/','giving':'/give/','faq':'/#questions','events':'/volunteer/','stories':'/our-clinic/','privacy-policy':'/legal/privacy/','cookie-policy':'/404/','terms-conditions':'/404/'};
// The archive’s prior deployed base path must remain reachable, including direct deep links.
for(const slug of ['',...pages.filter(x=>x!=='404')]) aliases['CanbyCLinic-Admin'+(slug?'/'+slug:'')]=slug?'/'+slug+'/':'/';
writeFileSync('scripts/redirects.json',JSON.stringify(aliases,null,2));
for(const [old,dest] of Object.entries(aliases)){
 mkdirSync(old,{recursive:true});writeFileSync(old+'/index.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Page moved</title><script>const target=new URL(${JSON.stringify(dest)},location.origin);target.search=location.search;if(location.hash)target.hash=location.hash;location.replace(target.href)</script><meta http-equiv="refresh" content="0;url=${dest}"></head><body><p>This page has moved. <a href="${dest}">Continue to the updated page</a>.</p></body></html>`);
}
writeFileSync('public/_redirects',Object.entries(aliases).flatMap(([old,d])=>[`/${old} ${d} 301`,`/${old}/ ${d} 301`]).join('\n')+'\n/* /404/index.html 404\n');
writeFileSync('vercel.json',JSON.stringify({cleanUrls:true,redirects:Object.entries(aliases).map(([old,d])=>({source:'/'+old,destination:d,permanent:true})),rewrites:[{source:'/:path*',destination:'/:path*/index.html'}]},null,2));
writeFileSync('scripts/entries.json',JSON.stringify(['index.html',...pages.map(s=>s+'/index.html'),...Object.keys(aliases).map(s=>s+'/index.html')]));
